export interface StyleConfig {
  bodyFontSize: number;
  lineHeight: number;
  paragraphMarginTop: number;
  paragraphSpacing: number;
  bodyFontFamily: string;
  bodyTextAlign: "left" | "center" | "right" | "justify" | "start";
  bodyWordBreak: "normal" | "break-all" | "break-word";
  h2Size: number;
  h3Size: number;
  headingWeight: number;
  headingLineHeight: number;
  headingMarginTop: number;
  headingMarginBottom: number;
  headingPaddingLeft: number;
  headingBorderLeftWidth: number;
  headingBorderLeftColor: string;
  h3MarginTop: number;
  h3MarginBottom: number;
  h3PaddingVertical: number;
  h3PaddingHorizontal: number;
  h3BorderLeftWidth: number;
  h3BorderRadius: number;
  h3BackgroundColor: string;
  primaryColor: string;
  secondaryColor: string;
  textColor: string;
  blockRadius: number;
  blockPadding: number;
  quoteFontSize: number;
  quoteLineHeight: number;
  quoteBgColor: string;
  quoteBorderColor: string;
  imageMargin: string;
  imageMaxHeight: number;
  imageBorder: string;
  imageBoxShadow: string;
  hrMargin: string;
  hrHeight: number;
  hrBackground: string;
  hrBorderTop: string;
}
